### ISSUE TITLE
Package metadata

### ISSUE THREAD

**Issue by mssun** [mesalock-linux/mkpkg#2]
I suggest to change the metadata from this:

```
env:
  pkgname: linux
  pkgver: 4.16.14

package:
  name: $pkgname
  version: $pkgver
  description: Linux kernel
  license: [GPL2]
```

to:

```
env:
  other_customized_variables1: xxxx
  other_customized_variables2: yyy

package:
  pkgname: linux
  pkgver: 4.16.14
  description: Linux kernel
  license: [GPL2]
```

The package metadata is pre-defined fields, currently we have `pkgname`, `pkgver`, `description`, `license`. These will provided as environmental variables when `prepare`, `build`, and `install` process.

Until now, we have these pre-defined environmental variables:`pkgname`, `pkgver`, `description`, `license`, `logdir`, `pkgdir`, `srcdir`.
