### ISSUE TITLE
The `copy_dir` function shoud handle symlinks

### ISSUE THREAD

**Issue by mssun** [mesalock-linux/mkpkg#7]
When copying a directory, the file could be a symlink.

https://github.com/mesalock-linux/mkpkg/blob/94df01bc51e9f00a87f247975096c9af046d6278/src/util.rs#L88-L94

The `std::fs::copy()` only throw error if the from path is not a file.

Reference:
  - https://doc.rust-lang.org/std/fs/struct.FileType.html#method.is_symlink
  - https://doc.rust-lang.org/std/fs/fn.copy.html

**Comment by Arcterus** [comment]
Ah, I didn't notice it failed on symlinks.  What package were you trying to build when you found the error?  I believe I've fixed it, but need to test against something.

**Comment by mssun** [comment]
Try this one:

```
 package:
   name: ripgrep
   version: 0.8.0
   description: ripgrep combines the usability of The Silver Searcher with the raw speed of grep
   license: [MIT, Unlicense]
   url: https://github.com/BurntSushi/ripgrep

   source:
     - git+https://github.com/BurntSushi/$name.git

   prepare:
     - cd "$name".git && git checkout -B 0.8.0

   build:
     - cd "$name".git && cargo build --release
     - cd "$name".git && cargo test

   install:
     - cd "$name".git && install -D -m744 target/release/"$name" -t "$pkgdir"/bin/
```

The `HomebrewFormula` is a symlink  (https://github.com/BurntSushi/ripgrep/blob/master/HomebrewFormula)
